import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "../components/menu"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "This Kitty Does Not Exist",
  description: "Generated by StyleGAN3",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header><Menu /></header>
        <main className="flex min-h-screen flex-col items-center p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
